<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-K6J63E8" name="com.qa.wellsFargo.TestScripts.TestCaseScripts" tests="13" failures="3" timestamp="2020-10-08T23:13:07 EDT" time="134.866" errors="0">
  <testcase name="logInTest" time="11.073" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="logInTest" time="11.363" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="logInTest" time="11.350" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="customerServiceDisplay" time="9.206" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedPersonalModule" time="8.650" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[]Personal&gt; but was:&lt;[selected
]Personal&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[]Personal> but was:<[selected
]Personal>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at com.qa.wellsFargo.TestScripts.TestCaseScripts.verifiedPersonalModule(TestCaseScripts.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifiedPersonalModule -->
  <system-out/>
  <testcase name="verifiedSmallBusinessModule" time="8.927" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedCommericalModule" time="9.337" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedFinancialEduModule" time="8.965" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedAbutWellsModule" time="9.180" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedPersonalClickAbleModule" time="12.761" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="verifiedBankingAndCreditFeature" time="12.086" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;Credit Card[]&gt; but was:&lt;Credit Card[s]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Credit Card[]> but was:<Credit Card[s]>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at com.qa.wellsFargo.TestScripts.TestCaseScripts.verifiedBankingAndCreditFeature(TestCaseScripts.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifiedBankingAndCreditFeature -->
  <system-out/>
  <testcase name="verifiedIndustryExpertiseLink" time="11.251" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts"/>
  <system-out/>
  <testcase name="aboutWellsFargoHomepage" time="10.717" classname="com.qa.wellsFargo.TestScripts.TestCaseScripts">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[a]bout Wells Fargo&gt; but was:&lt;[A]bout Wells Fargo&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[a]bout Wells Fargo> but was:<[A]bout Wells Fargo>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.Assert.assertEquals(Assert.java:107)
at com.qa.wellsFargo.TestScripts.TestCaseScripts.aboutWellsFargoHomepage(TestCaseScripts.java:137)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- aboutWellsFargoHomepage -->
  <system-out/>
</testsuite> <!-- com.qa.wellsFargo.TestScripts.TestCaseScripts -->
